# Generated by Django 3.1.11 on 2022-02-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220202_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Название'),
        ),
    ]
